### ISSUE TITLE
Get 'Permission denied (publickey)' when installing

### ISSUE THREAD

**Issue by rhulse** [varnish/newrelic_varnish_plugin#3]
Running 

```
bundle install
```

gives the following:

Fetching git@github.com:newrelic-platform/newrelic_plugin.git
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Git error: command `git clone 'git@github.com:newrelic-platform/newrelic_plugin.git' "/var/lib/gems/1.9.1/cache/bundler/git/newrelic_plugin-ee26a2accbf47c00562443b80ad79aaa92b63420" --bare
--no-hardlinks` in directory /root/newrelic_varnish_plugin-master has failed.

**Comment by dirtabulous** [comment]
Same here.

**Comment by tfheen** [comment]
I've now fixed this in git, test please?

**Comment by dirtabulous** [comment]
Yep.  Worked.  Thanks.
