### ISSUE TITLE
Instructions about "Go to the tags list" broken

### ISSUE THREAD

**Issue by Enalmada** [varnish/newrelic_varnish_plugin#9]
The git main page readme and the readme file in the zip both say to go to the tags list.  But this page is empty: https://github.com/varnish/newrelic_varnish_plugin/tags
That may cause some of your users some confusion.

**Comment by nalum** [comment]
I concur.

**Comment by darthsteven** [comment]
Yeah, this issue could actually just be about cutting a release, even if it was a beta version, it might be better than nothing.
